# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = false

mainSections = ["hizmetler"]
# robots = ""

disableImageOptimization = false
defaultBackgroundImage = "/img/hafif-celik-ev.jpg"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/hafif-celik-ev.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = false
  showMoreLinkDest = "hizmetler"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = false
  showSummary = false
  sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy","term","etiketler"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[languages.tr]
  languageCode = "tr"
  languageName = "Turkish"
  displayName = "TR"
  isoCode = "tr"
  weight = 1
  rtl = false
  title = "San Prefabrik"
# burayı aktifleştiriyorsan languages.tr.toml sil!!!
#  logo = "img/altinay-logo.png"
#  description = "San Prefabrik; Prefabrik, Tiny House, Metal Levha, Çelik Konstraksiyon, Tekirdağ, İstanbul, Silivri, Çatalca, için güvenilir üreticiniz."
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[author]
  name = "San Prefabrik"
  image = "img/cem-celal-altinay.png"
  headline = "San prefabrik olarak, yılların teknik ve esnaflık tecrübesi ile hizmet vermeye devam ediyoruz."
  bio = "Silivri'de yıllardır güvenilir, esnaf kurum."
  links = [
    { facebook = "https://www.facebook.com/profile.php?id=100094891414431" },
    { instagram = "https://www.instagram.com/sanprefabrik/" },
    { tiktok = "https://www.tiktok.com/@sanprefabrik" },
  ]

#[firebase]
#  apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
#  authDomain = "blowfish-21fff.firebaseapp.com"
#  projectId = "blowfish-21fff"
#  storageBucket = "blowfish-21fff.appspot.com"
#  messagingSenderId = "60108104191"
#  appId = "1:60108104191:web:039842ebe1370698b487ca"
#  measurementId = "G-PEDMYR1V0K"

#[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"
  
#googleAnalytics = "GTM-TVBTPJR"

#[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
